### ISSUE TITLE
CSV Format in Summary is misaligned

### ISSUE THREAD

**Issue by frvwfr2** [SvenskaSpel/locust-plugins#24]
https://github.com/SvenskaSpel/locust-plugins/blob/master/locust_plugins/transaction_manager.py#L173

Average Content Size and Requests/s never have their values filled in. Line 196 and 199 skip over two fields.

Something as simple as 

```
fields.append()
fields.append()
```

Would fix this misalignment. Or potentially remove them from the CSV header (lines 172-173), as the values should always (I think?) be empty.

**Comment by cyberw** [comment]
I think the issue is actually the number of percentiles.

PERCENTILES_TO_REPORT does not include 99.999% any more (it did at some time, but the printouts were so long that I removed it). I think the header printout should be changed to use the same way locust does here: https://github.com/locustio/locust/blob/master/locust/stats.py#L733

If you do that, and make sure it works it I will be happy to merge a PR :)

**Comment by ctstone** [comment]
I noticed this too. The [fields](https://github.com/SvenskaSpel/locust-plugins/blob/master/locust_plugins/transaction_manager.py#L231-L232) go from content-length to the percentiles, skipping values for `Requests/s` and `Failures/s`.

The other issue, as you mention, is that the default core locust [percentiles](https://github.com/locustio/locust/blob/master/locust/stats.py#L40) omit the 5-Nines, but that value is included in the plugin.

I think it makes sense to make the following changes:
1. Completely omit Content-Length, Request/s and Failures/s from the transaction summary. Since the transaction summary is its own file, I think it can define its own headers. Not sure if this has implication for the Web UI since I only run headless...
2. Make the percentile headers dynamic, based on the values from `locust.stats.PERCENTILEST_TO_REPORT`. This list is documented as [customizable](https://docs.locust.io/en/stable/configuration.html#customization-of-statistics-settings), so should not make assumptions about its values.
