### ISSUE TITLE
Selenium WebDriver fails when launch rate is higher then 0.25

### ISSUE THREAD

**Issue by alexeiser** [SvenskaSpel/locust-plugins#71]
Env:
Ubuntu 18.04
Selenium Grid v 4.1.2 (launched via docker like `docker run --log-driver=journald -e JAVA_OPTS=-Xmx512m -e SE_OPTS="--log-level FINE" -e SE_NODE_SESSION_TIMEOUT=1800 -e SE_SESSION_REQUEST_TIMEOUT=60 -e SE_SESSION_RETRY_INTERVAL=5 -e SE_NODE_OVERRIDE_MAX_SESSIONS=true -e SE_NODE_MAX_SESSIONS=120  -d -p 4444:4444 -p 7900:7900 --rm --shm-size="5g" --name sgrid  selenium/standalone-chrome:96.0` or natively using `xvfb-run java -Dwebdriver.chrome.driver=/usr/bin/chromedriver -jar selenium-server-standalone.jar standalone --session-timeout 10`

Using a simple webdriver based test like:
```
class GoogleUser(WebdriverUser):
    def on_start(self):
        self.client.set_window_size(1000, 1000)

    @task
    def homepage(self):
        with self.request(name=f"homepage") as request:
            self.client.get(f"https://google.com")
```

If the spawn rate is higher then 0.25 - the selenium grid will start sessions, but locust will never register the as a user.

Removing the sleep step at 
https://github.com/SvenskaSpel/locust-plugins/blob/master/locust_plugins/users/webdriver.py#L52

Seems to let the spawn rate work - although the second sleep - https://github.com/SvenskaSpel/locust-plugins/blob/master/locust_plugins/users/webdriver.py#L258 - does mean that it won't start more than 1 a second.

Removing both does seem to let the spawn rate work some what consistently. 

I don't know if this is an issue with my env - but I don't see any reason why the code as written wouldn't have worked. If you disable headless, and monitor over VNC - chrome windows are spawned for each user ... but locust doesn't start sending them commands.

**Comment by argh128** [comment]
Selenium grid (standalone) is what I have been using since I needed a load test platform and settled on locust. 

I use multiple workers, and each has its own selenium grid standalone server. 

As far as I can tell that’s the standard deployment mode for selenium these days. 

It’s worked quite well except for the issue described above where it doesn’t matter if I have 20 workers running on a 20 different 32 core hardware or a single worker - it can’t handle a ramp rate any higher then 0.25. 

I’ll try a local diff to remove the sleep and see if my results stay consistent
